// Drafted with AI assistance. Have a licensed attorney review before public
// launch, especially the AI-output ownership clause and arbitration clause
// enforceability in your jurisdiction.

import SiteHeader from '@/components/SiteHeader'
import SiteFooter from '@/components/SiteFooter'

export const metadata = { title: 'Terms of Use — Octane Files' }

export default function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main className="site-container pt-15 pb-20">
        <div className="max-w-180">
          <h1 className="text-heading font-bold tracking-[-0.03em] mb-2">Terms of Use</h1>
          <p className="text-body text-text-tertiary mb-10">Effective Date: July 10, 2026</p>

          <div className="prose">
            <p>
              These Terms of Use (these &quot;Terms&quot;) constitute a legally binding agreement
              between you (&quot;User&quot; or &quot;you&quot;) and Octane Files, a subsidiary of
              Freshdesign Interactive, Inc. (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot;
              or &quot;our&quot;), governing your access to and use of the Octane Files website,
              application, and related services (collectively, the &quot;Service&quot;). By
              accessing or using the Service, you agree to be bound by these Terms and our{' '}
              <a href="/privacy">Privacy Policy</a>, which is incorporated herein by reference. If
              you do not agree to these Terms, you must not access or use the Service.
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By creating an account, accessing, or using the Service in any way, you acknowledge
              that you have read, understood, and agree to be bound by these Terms. We may
              update these Terms from time to time as described in Section 17.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              Octane Files is an artificial intelligence content generation platform operated by
              Octane Files, a subsidiary of Freshdesign Interactive, Inc. The Service allows Users
              to submit prompts, instructions, and other inputs (&quot;Inputs&quot;) and receive
              content generated by artificial intelligence in response
              (&quot;Output&quot;). The Service and its features may change, be added to, or be
              discontinued at any time, at our sole discretion.
            </p>

            <h2>3. Eligibility</h2>
            <p>
              The Service is intended solely for individuals who are 18 years of age or older. By
              accessing or using the Service, you represent and warrant that you are at least 18
              years old and have the legal capacity to enter into these Terms. The Service is not
              directed to, and should not be used by, individuals under 18.
            </p>

            <h2>4. Accounts</h2>
            <p>
              Certain features of the Service may require you to register for an account. If and
              when account registration is required, you agree to: (a) provide accurate, current,
              and complete information; (b) maintain and promptly update such information; (c)
              maintain the confidentiality of your login credentials; and (d) accept
              responsibility for all activity that occurs under your account. You agree to notify
              us promptly of any unauthorized use of your account.
            </p>

            <h2>5. AI-Generated Content &amp; Disclaimer of Accuracy</h2>
            <p>
              THE OUTPUT GENERATED BY THE SERVICE IS PRODUCED USING ARTIFICIAL INTELLIGENCE AND
              IS PROVIDED &quot;AS IS,&quot; WITHOUT ANY WARRANTY OF ANY KIND. AI-GENERATED OUTPUT
              MAY BE INACCURATE, INCOMPLETE, OUTDATED, OR OTHERWISE UNSUITABLE FOR YOUR INTENDED
              PURPOSE. WE DO NOT WARRANT OR GUARANTEE THE ACCURACY, RELIABILITY, COMPLETENESS, OR
              QUALITY OF ANY OUTPUT. YOU ARE SOLELY RESPONSIBLE FOR INDEPENDENTLY REVIEWING,
              VERIFYING, AND EVALUATING ANY OUTPUT BEFORE RELYING ON IT FOR ANY PURPOSE, INCLUDING
              ANY PROFESSIONAL, LEGAL, FINANCIAL, MEDICAL, OR OTHER DECISION. WE EXPRESSLY
              DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED
              WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
              NON-INFRINGEMENT, WITH RESPECT TO ANY OUTPUT.
            </p>

            <h2>6. Intellectual Property / Ownership of Output</h2>
            <p>
              As between you and the Company, the Company retains all right, title, and interest
              in and to the Output generated by the Service, including all associated
              intellectual property rights.
            </p>
            <p>
              [CONFIRM: does the user receive any license to use the output they requested, or
              zero rights? Default to a limited, revocable, non-exclusive license to view/use
              output for personal reference unless told otherwise.]
            </p>
            <p>
              Unless otherwise agreed in writing, you receive a limited, non-exclusive,
              revocable, non-transferable license to view and use Output solely for your own
              personal, non-commercial reference. You may not sell, sublicense, distribute, or
              otherwise exploit Output except as expressly permitted by the Company in writing.
            </p>

            <h2>7. Third-Party AI Providers</h2>
            <p>
              The Service relies on third-party artificial intelligence providers, currently
              including Anthropic, Google Gemini, and Figma (each, an &quot;AI Provider&quot;),
              to generate Output. Your use of the Service is also subject to the applicable terms
              of service of each AI Provider. The Company is not responsible for, and disclaims
              all liability arising from, any outage, error, delay, inaccuracy, or other issue
              caused by or attributable to an AI Provider or its systems.
            </p>

            <h2>8. Payment Terms</h2>
            <p>
              The Service is currently offered free of charge, and no payment is required to use
              it. If and when Octane Files offers paid subscriptions or other paid features,
              payments will be processed by Stripe, Inc. (&quot;Stripe&quot;), and your use of any
              paid features will be subject to Stripe&apos;s terms of service in addition to any
              payment terms we make available to you at that time, including applicable fees,
              billing cycles, and refund policies. By providing payment information at that time,
              you authorize us (via Stripe) to charge the applicable fees to your chosen payment
              method.
            </p>

            <h2>9. Prohibited Uses</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable law, regulation, or third-party right;</li>
              <li>
                Infringe or misappropriate any intellectual property, privacy, or other
                proprietary right of any person or entity;
              </li>
              <li>
                Generate, request, or distribute content that is unlawful, harmful, threatening,
                abusive, harassing, defamatory, deceptive, or fraudulent;
              </li>
              <li>
                Generate content intended to impersonate any person or entity, or to mislead
                others as to the origin of content;
              </li>
              <li>
                Attempt to reverse engineer, decompile, disassemble, or otherwise attempt to
                derive the source code, underlying models, or algorithms of the Service or any AI
                Provider;
              </li>
              <li>
                Interfere with, disrupt, or attempt to gain unauthorized access to the Service,
                its systems, or its underlying infrastructure;
              </li>
              <li>
                Use automated means (including bots, scrapers, or crawlers) to access the Service
                without our prior written consent; or
              </li>
              <li>Use the Service in any manner that could disable, overburden, damage, or impair the Service.</li>
            </ul>
            <p>
              We reserve the right to investigate and take appropriate action against anyone who,
              in our sole discretion, violates this section, including removing content,
              suspending or terminating accounts, and reporting violations to law enforcement.
            </p>

            <h2>10. Intellectual Property in the Service Itself</h2>
            <p>
              The Service, including its software, design, text, graphics, logos, trademarks, and
              all other content provided by the Company (excluding Output), and all intellectual
              property rights therein, are owned by Freshdesign Interactive, Inc. or its
              licensors. Nothing in these Terms grants you any right, title, or interest in the
              Service or any of its underlying technology, except for the limited right to access
              and use the Service as expressly permitted by these Terms.
            </p>

            <h2>11. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE, INCLUDING ALL OUTPUT, IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS
              AVAILABLE&quot; BASIS, WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR
              STATUTORY, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY,
              FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT
              THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY DEFECTS
              WILL BE CORRECTED.
            </p>

            <h2>12. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY,
              FRESHDESIGN INTERACTIVE, INC., OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES,
              OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
              PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING OUT OF
              OR RELATED TO YOUR USE OF, OR INABILITY TO USE, THE SERVICE, WHETHER BASED ON
              WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT WE HAVE BEEN
              ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY LAW,
              OUR TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS OR THE
              SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO US FOR USE OF THE
              SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR
              (B) ONE HUNDRED U.S. DOLLARS ($100).
            </p>

            <h2>13. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless the Company, Freshdesign
              Interactive, Inc., and their respective officers, directors, employees, and agents
              from and against any claims, liabilities, damages, losses, and expenses, including
              reasonable attorneys&apos; fees, arising out of or in any way connected with: (a)
              your access to or use of the Service; (b) your Inputs or your use of any Output; (c)
              your violation of these Terms; or (d) your violation of any applicable law or the
              rights of any third party.
            </p>

            <h2>14. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time, with or without
              notice, for any reason or no reason, including if we believe you have violated
              these Terms. You may stop using the Service at any time. Provisions of these Terms
              that by their nature should survive termination (including, without limitation,
              Sections 5, 6, 9, 10, 11, 12, 13, 15, and 16) will survive any termination of these
              Terms.
            </p>

            <h2>15. Dispute Resolution: Binding Arbitration &amp; Class Action Waiver</h2>
            <p>PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS.</p>
            <p>
              <strong>(a) Agreement to Arbitrate.</strong> You and the Company agree that any
              dispute, claim, or controversy arising out of or relating to these Terms or the
              Service (a &quot;Dispute&quot;) will be resolved by binding arbitration
              administered by the American Arbitration Association (&quot;AAA&quot;) under its
              Consumer Arbitration Rules then in effect, rather than in court, except that either
              party may bring an individual action in small claims court.
            </p>
            <p>
              <strong>(b) Class Action and Jury Trial Waiver.</strong> YOU AND THE COMPANY AGREE
              THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY, AND NOT
              AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
              YOU AND THE COMPANY EACH WAIVE ANY RIGHT TO A JURY TRIAL.
            </p>
            <p>
              <strong>(c) Opt-Out Right.</strong> You may opt out of this arbitration agreement by
              sending written notice to the address in Section 19 within thirty (30) days of the
              date you first accept these Terms. Your notice must include your name, the email
              address associated with your account (if any), and a clear statement that you wish
              to opt out of this arbitration agreement. If you opt out, neither you nor the
              Company will be required to arbitrate Disputes, but all other provisions of these
              Terms, including the class action waiver, will continue to apply to the maximum
              extent permitted by law.
            </p>
            <p>
              <strong>(d) Severability.</strong> If any part of this Section 15 is found to be
              unenforceable, the remainder of this Section 15 will remain in full force and
              effect.
            </p>

            <h2>16. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the State
              of California, without regard to its conflict-of-laws principles.
            </p>

            <h2>17. Changes to These Terms</h2>
            <p>
              We may modify these Terms from time to time. If we make material changes, we will
              update the &quot;Effective Date&quot; at the top of these Terms. Your continued use
              of the Service after any changes become effective constitutes your acceptance of
              the revised Terms.
            </p>

            <h2>18. Miscellaneous</h2>
            <p>
              <strong>(a) Severability.</strong> If any provision of these Terms is held to be
              invalid or unenforceable, that provision will be limited or eliminated to the
              minimum extent necessary, and the remaining provisions will remain in full force
              and effect.
            </p>
            <p>
              <strong>(b) Entire Agreement.</strong> These Terms, together with our Privacy
              Policy, constitute the entire agreement between you and the Company regarding the
              Service and supersede any prior agreements.
            </p>
            <p>
              <strong>(c) No Waiver.</strong> Our failure to enforce any right or provision of
              these Terms will not be deemed a waiver of such right or provision.
            </p>
            <p>
              <strong>(d) Assignment.</strong> You may not assign or transfer these Terms without
              our prior written consent. We may assign these Terms without restriction, including
              in connection with a merger, acquisition, or sale of assets.
            </p>
            <p>
              <strong>(e) Force Majeure.</strong> We will not be liable for any delay or failure
              to perform resulting from causes outside our reasonable control.
            </p>

            <h2>19. Contact Information</h2>
            <p>If you have questions about these Terms, please contact us at:</p>
            <p>
              Octane Files
              <br />
              c/o Freshdesign Interactive, Inc.
              <br />
              130 Umbarger Road
              <br />
              San Jose, CA 95111
              <br />
              Email: <a href="mailto:info@freshdesign.com">info@freshdesign.com</a>
            </p>
          </div>
        </div>
      </main>
      <SiteFooter />
    </>
  )
}
